<?php
echo "Registr form<br>";
use App\Controller\Index;

use Base\Despetcher;
$despetch = new Despetcher();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация и Авторизация</title>
</head>
<body>
Регистрация
<br>
<br>
<form action="createUser" method="post">
    Login:   <input type="text" name="login" value=""><br>
Password:  <input type="text" name="password" value=""><br>
email:  <input type="text" name="email" value=""><br>
    <input type="submit" value="registr">
</form>
<br>
<br>
<br>
Авторизация
<br>
<br>
<form action="login" method="post">
    Login:   <input type="text" name="login" value=""><br>
Password:  <input type="text" name="password" value=""><br>
email:  <input type="text" name="email" value=""><br>
    <input type="submit" value="login">
</form>
<br>
<br>
<br>
<?php //if ($this->error)
//{
//echo 'Ошибка ' . $this->error;}?>
</body>
</html>


