<?php


namespace Base;

use App\Model\User;

class ControllerUser extends Controller
{
        public function preAction()
        {
            parent::preAction(); // TODO: Change the autogenerated stub
            if (!$this->USER){
                $this->redirect("/Index/register");
            }
        }

}